### ISSUE TITLE
Blank white screen after building

### ISSUE THREAD

**Issue by vasilymilovidov** [ghalestrilo/seg-react#8]
I tried to build verso with yarn install and yarn tauri dev, but it gives me a blank white screen. There are some warnings about unused imports in the terminal, but nothing critical. 
<img width="797" alt="image" src="https://user-images.githubusercontent.com/27685069/216976003-981e68ff-8e0b-438f-ae39-20feaf196df8.png">

**Comment by ghalestrilo** [comment]
Thanks for flagging, looking into this. Seems like a promise is failing and causing the app to crash, haven't found the cause yet.

**Comment by ghalestrilo** [comment]
The app builds normally now - the problem was using `process.env`, which works in development but fails within the compiled binary.
I had to disable spawning REPLs for the time being but will add the feature back over the next few days.
Thanks again for reporting this
